In [1]:
import pandas as pd
import numpy as np

import scipy
# from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns
import datetime
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import seaborn as sns

In [2]:
# read CSV
df=pd.read_csv("unifed_csv_without_duplicated_company.csv")
df.info(max_cols=1000)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37198 entries, 0 to 37197
Data columns (total 132 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   company_uuid                      37198 non-null  object 
 1   country_code                      33609 non-null  object 
 2   region                            33609 non-null  object 
 3   city                              33609 non-null  object 
 4   operating                         37198 non-null  int64  
 5   closed                            37198 non-null  int64  
 6   success                           37198 non-null  int64  
 7   success_acquired                  37198 non-null  int64  
 8   success_ipo                       37198 non-null  int64  
 9   num_funding_rounds                12036 non-null  float64
 10  total_funding_usd                 9093 non-null   float64
 11  founded_on                        37198 non-null  float64
 12  las

In [3]:
df

company_uuid country_code         region  \
0      0001a6ec-e7e9-4d1b-8a77-adb5ac815420          JPN          Tokyo   
1      0003f244-79d0-6178-353e-33dabaf3b2c6          USA     California   
2      00057beb-5724-c809-5cd2-a0a7c6b017aa          ESP         Madrid   
3      000ab460-8462-450d-ab34-b3c54fc252fd          LKA        Western   
4      000ad7a8-b868-f301-5f00-2a3361288fc9          USA       New York   
...                                     ...          ...            ...   
37193  fff9249a-baea-49a9-baca-a57b28ee7e6f          USA     California   
37194  fffa7546-aba8-5bbf-11a9-105d61b0dd0e          NLD  Noord-Brabant   
37195  fffbd05f-57b7-4fdc-94a6-be656719db8c          CHN       Zhejiang   
37196  fffe3b0b-8545-4414-9c0e-a3f961c4e420          CHN      Guangdong   
37197  ffffabce-6d4a-b3d1-13c0-4e90cedf5270          USA       New York   

                city  operating  closed  success  success_acquired  \
0              Tokyo          1       0        0                 0   
1      San Francisco          1       0        0                 0   
2             Madrid          1       0        0                 0   
3            Colombo          1       0        0                 0   
4           Brooklyn          1       0        0                 0   
...              ...        ...     ...      ...               ...   
37193    Los Angeles          1       0        0                 0   
37194       Maaskant          1       0        0                 0   
37195         Ningbo          1       0        0                 0   
37196      Guangzhou          1       0        0                 0   
37197       New York          1       0        0                 0   

       success_ipo  num_funding_rounds  ...  has_acquisitions  has_ipo  \
0                0                 NaN  ...                 0        0   
1                0                 NaN  ...                 0        0   
2                0                 NaN  ...                 0        0   
3                0                 NaN  ...                 0        0   
4                0                 2.0  ...                 0        0   
...            ...                 ...  ...               ...      ...   
37193            0                 NaN  ...                 0        0   
37194            0                 NaN  ...                 0        0   
37195            0                 NaN  ...                 0        0   
37196            0                 1.0  ...                 0        0   
37197            0                 6.0  ...                 0        0   

      time_in_year                                   investment_delta  \
0              NaN                                                NaN   
1              NaN                                                NaN   
2              NaN                                                NaN   
3              NaN                                                NaN   
4              NaN                                                NaN   
...            ...                                                ...   
37193          NaN                                                NaN   
37194          NaN                                                NaN   
37195          NaN                                                NaN   
37196          NaN                                                NaN   
37197       6.0795  ['grant to angel', 'angel to product_crowdfund...   

                                       norm_amount_delta  \
0                                                    NaN   
1                                                    NaN   
2                                                    NaN   
3                                                    NaN   
4                                                    NaN   
...                                                  ...   
37193                                                NaN   
37194                                      

In [4]:
keep_col = ['operating', 'closed', 'success', 'Financial Services', 'FinTech', 'Blockchain', 'Cryptocurrency', 'fund_rd_raised_amount_usd', 'investment_count', 'any_partner', 'event_count', 'job_duration', 'gender_male', 'gender_female', 'degree_type', 'subject_Computer Science', 'subject_Economics', 'subject_Finance', 'USA', 'GBR', 'CHN', 'city_London', 'city_New_York', 'city_San_Francisco', 'mean_norm_amount_delta', 'max_norm_amount_delta','momentum','ROI']
df = df[keep_col]

In [5]:
df['fund_rd_raised_amount_usd'] = np.log(df['fund_rd_raised_amount_usd'])

/opt/anaconda3/envs/UBS/lib/python3.8/site-packages/pandas/core/series.py:726: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
<ipython-input-5-e791c8fc62a9>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['fund_rd_raised_amount_usd'] = np.log(df['fund_rd_raised_amount_usd'])


In [6]:
df['ROI'].replace([np.inf, -np.inf], np.nan, inplace=True)
df['momentum'].replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)

/opt/anaconda3/envs/UBS/lib/python3.8/site-packages/pandas/core/series.py:4575: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(
<ipython-input-6-4ac641e40c33>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace=True)


In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2860 entries, 10 to 37197
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   operating                  2860 non-null   int64  
 1   closed                     2860 non-null   int64  
 2   success                    2860 non-null   int64  
 3   Financial Services         2860 non-null   int64  
 4   FinTech                    2860 non-null   int64  
 5   Blockchain                 2860 non-null   int64  
 6   Cryptocurrency             2860 non-null   int64  
 7   fund_rd_raised_amount_usd  2860 non-null   float64
 8   investment_count           2860 non-null   float64
 9   any_partner                2860 non-null   float64
 10  event_count                2860 non-null   float64
 11  job_duration               2860 non-null   float64
 12  gender_male                2860 non-null   float64
 13  gender_female              2860 non-null   flo

In [8]:
df['momentum'] = df['momentum'].apply(lambda x: list(x[1:-1].split(", ")))
def conversion(col):
    summ = 0
    leng = 0
    for each in col:
        if "inf" in each:
            return np.inf
            break
        each = float(each)
        summ+=each
        leng += 1
    return (summ/leng)
df['mean_momentum'] = df['momentum'].apply(conversion)
df.drop(columns=['momentum'], inplace = True)
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)

<ipython-input-8-35dff9140f41>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['momentum'] = df['momentum'].apply(lambda x: list(x[1:-1].split(", ")))
<ipython-input-8-35dff9140f41>:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['mean_momentum'] = df['momentum'].apply(conversion)
/opt/anaconda3/envs/UBS/lib/python3.8/site-packages/pandas/core/frame.py:4167: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pand

In [9]:
df.reset_index(drop=True)

operating  closed  success  Financial Services  FinTech  Blockchain  \
0             1       0        0                   0        0           0   
1             0       0        1                   0        0           0   
2             1       0        0                   0        0           0   
3             1       0        0                   0        0           0   
4             1       0        0                   0        0           0   
...         ...     ...      ...                 ...      ...         ...   
2792          1       0        0                   0        0           0   
2793          1       0        0                   0        0           0   
2794          1       0        0                   0        0           0   
2795          1       0        0                   0        0           0   
2796          1       0        0                   0        0           0   

      Cryptocurrency  fund_rd_raised_amount_usd  investment_count  \
0                  0                  13.171154               0.0   
1                  0                  14.500520               0.0   
2                  0                  15.317455             315.0   
3                  0                  13.981322               0.0   
4                  0                  14.508658             244.0   
...              ...                        ...               ...   
2792               0                  18.560443               0.0   
2793               0                  14.760395               0.0   
2794               0                  15.607270               0.0   
2795               0                  13.815511               0.0   
2796               0                  11.314475               0.0   

      any_partner  ...  USA  GBR  CHN  city_London  city_New_York  \
0             0.0  ...    1    0    0            0              0   
1             0.0  ...    0    0    0            0              0   
2             1.0  ...    0    0    0            0              0   
3             0.0  ...    0    0    0            0              0   
4             1.0  ...    1    0    0            0              0   
...           ...  ...  ...  ...  ...          ...            ...   
2792          0.0  ...    0    0    0            0              0   
2793          0.0  ...    0    0    0            0              0   
2794          0.0  ...    0    0    0            0              0   
2795          0.0  ...    1    0    0            0              0   
2796          0.0  ...    1    0    0            0              1   

      city_San_Francisco  mean_norm_amount_delta  max_norm_amount_delta  \
0                      1                1.478261               1.478261   
1                      0                0.557546               1.246517   
2                      0                0.418108               0.880874   
3                      0                0.515446               0.515446   
4                      0                0.857143               0.857143   
...                  ...                     ...                    ...   
2792                   0                0.375211               1.547816   
2793                   0                0.948442               0.948442   
2794                   0                0.494253               1.333333   
2795                   0                0.964286               1.428571   
2796                   0                0.836687               1.368421   

           ROI  mean_momentum  
0     3.155306       3.155306  
1     0.303599       1.030903  
2    -0.032928       0.325569  
3     0.248205       0.248205  
4     0.999467       0.999467  
...        ...            ...  
2792  0.733519       0.529492  
2793  0.551227       0.551227  
2794 -0.223943       3.090078  
2795  0.352082       0.442850  
2796  4.161865       1.750127  

[2797 rows x 28 columns]

In [10]:
#step 1
y = df['closed']
X = df.iloc[:,7:-4]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_test)
print('Accuracy of logistic regression classifier on closed companies as threshold: {:.2f}'.format(logreg.score(X_test, y_test)))

print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

Accuracy of logistic regression classifier on closed companies as threshold: 0.97
[[812   0]
 [ 28   0]]
              precision    recall  f1-score   support

           0       0.97      1.00      0.98       812
           1       0.00      0.00      0.00        28

    accuracy                           0.97       840
   macro avg       0.48      0.50      0.49       840
weighted avg       0.93      0.97      0.95       840



/opt/anaconda3/envs/UBS/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/envs/UBS/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [11]:
#step 1 predicting closed / not closed
y = df['success']
X = df.iloc[:,7:-4]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_test)
print('Accuracy of logistic regression classifier on closed companies as threshold: {:.2f}'.format(logreg.score(X_test, y_test)))

print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

Accuracy of logistic regression classifier on closed companies as threshold: 0.92
[[772   0]
 [ 68   0]]
              precision    recall  f1-score   support

           0       0.92      1.00      0.96       772
           1       0.00      0.00      0.00        68

    accuracy                           0.92       840
   macro avg       0.46      0.50      0.48       840
weighted avg       0.84      0.92      0.88       840



/opt/anaconda3/envs/UBS/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/envs/UBS/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [12]:
# step 2: predicting ROI

y1 = df['mean_norm_amount_delta']
y2 = df['max_norm_amount_delta']
y3 = df['mean_momentum']
y4 = df['ROI']
X = df.drop(columns=['mean_norm_amount_delta', 'mean_momentum', 'ROI', 'max_norm_amount_delta'])

In [13]:
y1_threshold = np.percentile(df['mean_norm_amount_delta'], [75])
y2_threshold = np.percentile(df['max_norm_amount_delta'], [75])
y3_threshold = np.percentile(df['mean_momentum'], [75])
y4_threshold = np.percentile(df['ROI'], [75])
y1 = df['mean_norm_amount_delta'].apply(lambda x: 1 if x >= y1_threshold else 0)
y2 = df['max_norm_amount_delta'].apply(lambda x: 1 if x >= y2_threshold else 0)
y3 = df['mean_momentum'].apply(lambda x: 1 if x >= y3_threshold else 0)
y4 = df['ROI'].apply(lambda x: 1 if x >= y4_threshold else 0)

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y1, test_size=0.3, random_state=0)
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_test)
print('Accuracy of logistic regression classifier on mean_delta with 75% as threshold: {:.2f}'.format(logreg.score(X_test, y_test)))

print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

Accuracy of logistic regression classifier on mean_delta with 75% as threshold: 0.73
[[614   1]
 [224   1]]
              precision    recall  f1-score   support

           0       0.73      1.00      0.85       615
           1       0.50      0.00      0.01       225

    accuracy                           0.73       840
   macro avg       0.62      0.50      0.43       840
weighted avg       0.67      0.73      0.62       840



/opt/anaconda3/envs/UBS/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y2, test_size=0.3, random_state=0)
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_test)
print('Accuracy of logistic regression classifier on max_delta with 75% as threshold: {:.2f}'.format(logreg.score(X_test, y_test)))

print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

Accuracy of logistic regression classifier on max_delta with 75% as threshold: 0.74
[[625   3]
 [212   0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.85       628
           1       0.00      0.00      0.00       212

    accuracy                           0.74       840
   macro avg       0.37      0.50      0.43       840
weighted avg       0.56      0.74      0.64       840



/opt/anaconda3/envs/UBS/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y3, test_size=0.3, random_state=0)
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_test)
print('Accuracy of logistic regression classifier on mean_momentum with 75% as threshold: {:.2f}'.format(logreg.score(X_test, y_test)))

print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

Accuracy of logistic regression classifier on mean_momentum with 75% as threshold: 0.76
[[638   1]
 [200   1]]
              precision    recall  f1-score   support

           0       0.76      1.00      0.86       639
           1       0.50      0.00      0.01       201

    accuracy                           0.76       840
   macro avg       0.63      0.50      0.44       840
weighted avg       0.70      0.76      0.66       840



/opt/anaconda3/envs/UBS/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y4, test_size=0.3, random_state=0)
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_test)
print('Accuracy of logistic regression classifier on ROI(latest momentum) with 75% as threshold: {:.2f}'.format(logreg.score(X_test, y_test)))

print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

Accuracy of logistic regression classifier on ROI(latest momentum) with 75% as threshold: 0.74
[[623   2]
 [215   0]]
              precision    recall  f1-score   support

           0       0.74      1.00      0.85       625
           1       0.00      0.00      0.00       215

    accuracy                           0.74       840
   macro avg       0.37      0.50      0.43       840
weighted avg       0.55      0.74      0.63       840



/opt/anaconda3/envs/UBS/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [18]:
y1_threshold = np.percentile(df['mean_norm_amount_delta'], [90])
y2_threshold = np.percentile(df['max_norm_amount_delta'], [90])
y3_threshold = np.percentile(df['mean_momentum'], [90])
y4_threshold = np.percentile(df['ROI'], [90])
y1 = df['mean_norm_amount_delta'].apply(lambda x: 1 if x >= y1_threshold else 0)
y2 = df['max_norm_amount_delta'].apply(lambda x: 1 if x >= y2_threshold else 0)
y3 = df['mean_momentum'].apply(lambda x: 1 if x >= y3_threshold else 0)
y4 = df['ROI'].apply(lambda x: 1 if x >= y4_threshold else 0)

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y1, test_size=0.3, random_state=0)
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_test)
print('Accuracy of logistic regression classifier on mean_delta with 90% as threshold: {:.2f}'.format(logreg.score(X_test, y_test)))

print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

Accuracy of logistic regression classifier on mean_delta with 90% as threshold: 0.89
[[751   0]
 [ 89   0]]
              precision    recall  f1-score   support

           0       0.89      1.00      0.94       751
           1       0.00      0.00      0.00        89

    accuracy                           0.89       840
   macro avg       0.45      0.50      0.47       840
weighted avg       0.80      0.89      0.84       840



/opt/anaconda3/envs/UBS/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/envs/UBS/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y2, test_size=0.3, random_state=0)
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_test)
print('Accuracy of logistic regression classifier on max_delta with 90% as threshold: {:.2f}'.format(logreg.score(X_test, y_test)))

print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

Accuracy of logistic regression classifier on max_delta with 90% as threshold: 0.90
[[755   0]
 [ 85   0]]
              precision    recall  f1-score   support

           0       0.90      1.00      0.95       755
           1       0.00      0.00      0.00        85

    accuracy                           0.90       840
   macro avg       0.45      0.50      0.47       840
weighted avg       0.81      0.90      0.85       840



/opt/anaconda3/envs/UBS/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/envs/UBS/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y3, test_size=0.3, random_state=0)
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_test)
print('Accuracy of logistic regression classifier on mean_momentum with 90% as threshold: {:.2f}'.format(logreg.score(X_test, y_test)))

print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

Accuracy of logistic regression classifier on mean_momentum with 90% as threshold: 0.90
[[755   0]
 [ 85   0]]
              precision    recall  f1-score   support

           0       0.90      1.00      0.95       755
           1       0.00      0.00      0.00        85

    accuracy                           0.90       840
   macro avg       0.45      0.50      0.47       840
weighted avg       0.81      0.90      0.85       840



/opt/anaconda3/envs/UBS/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/envs/UBS/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y4, test_size=0.3, random_state=0)
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_test)
print('Accuracy of logistic regression classifier on ROI(latest momentum) with 90% as threshold: {:.2f}'.format(logreg.score(X_test, y_test)))

print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

Accuracy of logistic regression classifier on ROI(latest momentum) with 90% as threshold: 0.91
[[766   0]
 [ 74   0]]
              precision    recall  f1-score   support

           0       0.91      1.00      0.95       766
           1       0.00      0.00      0.00        74

    accuracy                           0.91       840
   macro avg       0.46      0.50      0.48       840
weighted avg       0.83      0.91      0.87       840



/opt/anaconda3/envs/UBS/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/envs/UBS/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
